#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Compile solvers (and their corresponding libraries)
#wmake -all $targetType solvers
applications/solvers/heatTransfer/directChillFoam/Allwmake $targetType $*

# Compile general-purpose libraries
wmake -all $targetType src

#------------------------------------------------------------------------------
